spring:  data:    neo4j:      uri: bolt://localhost:7687

---
spring:    config:      activate:        on-profile: local     data:      neo4j:        uri: bolt://localhost:7687name: local-YAML
environment: local
---
spring:    config:      activate:        on-profile: prod 
name: prod-YAML
environment: production