spring:  data:    neo4j:      uri: bolt://localhost:7687

---
spring:
    profiles: local    data:      neo4j:        uri: bolt://localhost:7687name: local-YAML
environment: local
---
spring:
    profiles: prod
name: prod-YAML
environment: production